// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmgdqgnwvknqiwkpnogj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxtZ2RxZ253dmtucWl3a3Bub2dqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MzkxOTQsImV4cCI6MjA3MjExNTE5NH0.rCWNQTuSdqRhXjlqiCkrLdi7Cow_uukPPzye62shdck";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});